# Generated by Django 4.0.3 on 2024-04-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(max_length=100)),
                ('doc_ambt_cont', models.TextField()),
                ('doc_date', models.CharField(max_length=30)),
                ('doc_title', models.CharField(blank=True, max_length=200, null=True)),
                ('doc_pontos_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('pontos', models.IntegerField(default=0)),
                ('nivel_de_experiencia', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InputLog',
            fields=[
                ('input_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_type', models.IntegerField(default=None)),
                ('input_content', models.TextField()),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.document')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.user')),
            ],
        ),
    ]
