# Generated by Django 4.0.3 on 2024-04-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
