# Generated by Django 4.0.3 on 2024-04-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_document_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_date',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
