# Generated by Django 4.0.3 on 2024-04-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_document_doc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_ambt_cont',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.IntegerField(max_length=100),
        ),
    ]
