# Generated by Django 4.0.3 on 2024-04-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_document_doc_ambt_cont_alter_document_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_pontos_index',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
