# Generated by Django 4.0.3 on 2024-04-19 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_userpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputlog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='inputlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
