# Generated by Django 4.0.3 on 2024-04-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_inputlog_user_id_inputlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputlog',
            name='input_score',
            field=models.IntegerField(default=0),
        ),
    ]
